SERVER_PORT: '8080'
DB_USERNAME: root
SERVLET_CONTEXT_PATH: /api/v1
DB_URL: jdbc:mysql://localhost:3306/Releve-Bancaire-CDG
APPLICATION_NAME: relevebancaire
DB_PASSWORD: root
spring:
  cloud:
    config:
      enabled: true
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: 'true'
    datasource:
      hikari:
        username: root
        connection-timeout: '5000'
        jdbc-url: jdbc:mysql://localhost:3306/Releve-Bancaire-CDG
        pool-name: pool-relevebancaire
        maximum-pool-size: '10'
        password: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/Releve-Bancaire-CDG
      tomcat:
        validation-query: SELECT 1
        test-while-idle: 'true'
    main:
      allow-bean-definition-overriding: 'true'
    jackson:
      serialization:
        fail-on-empty-beans: 'false'
  application:
    name: ${APPLICATION_NAME}
  jmx:
    enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: log

  flyway:
    enabled: false

  server:
    address: 127.0.0.1
    security:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always
    port: ${SERVER_PORT}
    servlet:
      context-path: ${SERVLET_CONTEXT_PATH}