SERVER_PORT: '8080'
DB_USERNAME: root
SERVLET_CONTEXT_PATH: /api/v1
DB_URL: jdbc:mysql://localhost:3306/Releve-Bancaire-CDG
APPLICATION_NAME: relevebancaire
DB_PASSWORD: root
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: '5000'
      maximum-pool-size: '10'
      pool-name: pool-relevebancaire
      jdbc-url: jdbc:mysql://localhost:3306/Releve-Bancaire-CDG
      username: root
      password: root
    tomcat:
      test-while-idle: 'true'
      validation-query: SELECT 1
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  main:
    allow-bean-definition-overriding: 'true'
  application:
    name: ${APPLICATION_NAME}
  jmx:
    enabled: true
    banner-mode: log

  flyway:
    enabled: false

  server:
    address: 127.0.0.1
    security:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always
    port: ${SERVER_PORT}
    servlet:
      context-path: ${SERVLET_CONTEXT_PATH}