spring:
    application:
        name: relevebancaire
    jmx:
        enabled: true
    main:
        allow-bean-definition-overriding: true
        banner-mode: log

    flyway:
        enabled: false

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            connection-timeout: 5000
            pool-name: pool-relevebancaire
            jdbc-url: jdbc:mysql://localhost:3306/releve-bancaire-cdg?useSSL=false
            username: root
            password: root

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQL8Dialect

server:
    address: 127.0.0.1
    port: 8080
    servlet:
        context-path: /api/v1